spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wurenzu?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port:6379
    host:127.0.0.1